name: quomia
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.2

environment:
  sdk: ^3.5.2

dependencies:
  carousel_slider: ^5.0.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/videos/sample_video.mp4
    - assets/animations/intro.json
    - assets/animations/hourglass.json
    - assets/images/quomia_logo.png